DELIMITER = ','

WORD_FREQ_COUNT = 49
CHAR_FREQ_COUNT = 7

WARNING_IGNORE = 'ignore'
TRUE_NEGATIVE = 'True Negative'
TRUE_POSITIVE = 'True Positive'
FALSE_POSITIVE = 'False Positive'
FALSE_NEGATIVE = 'False Negative'
FALSE_POSITIVE_RATE = 'False Positive Rate'
FALSE_NEGATIVE_RATE = 'False Negative Rate'
OVERALL_ERROR_RATE = 'Overall Error Rate'
MEAN_ABSOLUTE_ERROR = 'Mean Absolute Error'
MEAN_SQUARED_ERROR = 'Mean Squared Error'
PRECISION = 'Precision'
RECALL = 'Recall'
F1_SCORE = 'F1 Score'
AVG_FALSE_NEG_RATE = 'Average FNR'
AVG_FALSE_POS_RATE = 'Average FPR'
AVG_OVERALL_ERROR_RATE = 'Average OverallError Rate'
AVG_PRECISION = 'Average Precision'
AVG_RECALL = 'Average Recall'
AVG_F1_SCORE = 'Average F1 Score'

WORD_FREQUENCY = 'Word_Freq'
CHAR_FREQUENCY = 'Char_Freq'
CAP_RUN_LENGTH_AVG = 'Capital_Run_Length_Avg'
CAP_RUN_LENGTH_LONGEST = 'Capital_Run_Length_Longest'
CAP_RUN_LENGTH_TOTAL = 'Capital_Run_Length_Total'
CLASS_LABEL = 'Class Label'
